GinPort: 8080
OpenAIKey: "sk-****"
# OpenAIKey:
#   - "sk-****"
#   - "sk-****"
DBName: "chat.db"
InitUsers:
  - Username: userAAA
    Token: abcd
  - Username: userBBB
    Token: bbcd
  - Username: user111
    Token: ddcd
